apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-bclz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-bclz
    app.kubernetes.io/part-of: integ-app-snhf
  name: hacbs-test-project-bclz
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-bclz
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-bclz
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/nbe-e2e-gbep-tenant/integ-app-snhf/hacbs-test-project-bclz@sha256:7f6a81d52a7e1eaefebf12569c8d8f4bb9eccfaa583e832c2e0bb2b432b82f2b
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
